# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\wkspaces\EPLVTS01_PY_TOOLS\Src\GUI\resources\debug_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_container(object):
    def setupUi(self, container):
        container.setObjectName("container")
        container.resize(696, 383)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(container.sizePolicy().hasHeightForWidth())
        container.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(container)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.info_frame = QtWidgets.QFrame(container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_frame.sizePolicy().hasHeightForWidth())
        self.info_frame.setSizePolicy(sizePolicy)
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setLineWidth(0)
        self.info_frame.setObjectName("info_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.info_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.info_frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.info_frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_bus = QtWidgets.QComboBox(self.info_frame)
        self.comboBox_bus.setObjectName("comboBox_bus")
        self.horizontalLayout.addWidget(self.comboBox_bus)
        self.label_2 = QtWidgets.QLabel(self.info_frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_channel = QtWidgets.QComboBox(self.info_frame)
        self.comboBox_channel.setObjectName("comboBox_channel")
        self.horizontalLayout.addWidget(self.comboBox_channel)
        self.verticalLayout.addWidget(self.info_frame)
        self.listView = QtWidgets.QListView(container)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.frame = QtWidgets.QFrame(container)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(container)
        QtCore.QMetaObject.connectSlotsByName(container)

    def retranslateUi(self, container):
        _translate = QtCore.QCoreApplication.translate
        container.setWindowTitle(_translate("container", "Frame"))
        self.pushButton_2.setText(_translate("container", "Clear window"))
        self.label.setText(_translate("container", "Bus type:"))
        self.label_2.setText(_translate("container", "Channel"))
        self.pushButton.setText(_translate("container", "Send"))
