# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\wkspaces\EPLVTS01_PY_TOOLS\Src\GUI\resources\system_dialog_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setObjectName("tabWidget")
        self.Overall_tab = QtWidgets.QWidget()
        self.Overall_tab.setObjectName("Overall_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Overall_tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.Overall_tab)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.tabWidget.addTab(self.Overall_tab, "")
        self.System_tab = QtWidgets.QWidget()
        self.System_tab.setObjectName("System_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.System_tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.System_tab)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout.addWidget(self.plainTextEdit_2)
        self.tabWidget.addTab(self.System_tab, "")
        self.Test_tab = QtWidgets.QWidget()
        self.Test_tab.setObjectName("Test_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Test_tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.Test_tab)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.verticalLayout_3.addWidget(self.plainTextEdit_3)
        self.tabWidget.addTab(self.Test_tab, "")
        self.verticalLayout_4.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Overall_tab), _translate("Form", "Overall"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.System_tab), _translate("Form", "System"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Test_tab), _translate("Form", "Test"))
