# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\wkspaces\EPLVTS01_PY_TOOLS\Src\GUI\resources\system_dialog_dock.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(441, 292)
        DockWidget.setFloating(True)
        DockWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        DockWidget.setWindowTitle("System dialog")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setObjectName("tabWidget")
        self.Overall_tab = QtWidgets.QWidget()
        self.Overall_tab.setObjectName("Overall_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Overall_tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Overall_tab_text = QtWidgets.QPlainTextEdit(self.Overall_tab)
        self.Overall_tab_text.setObjectName("Overall_tab_text")
        self.verticalLayout_3.addWidget(self.Overall_tab_text)
        self.tabWidget.addTab(self.Overall_tab, "Tab 1")
        self.System_tab = QtWidgets.QWidget()
        self.System_tab.setObjectName("System_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.System_tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.System_tab_text = QtWidgets.QPlainTextEdit(self.System_tab)
        self.System_tab_text.setObjectName("System_tab_text")
        self.verticalLayout.addWidget(self.System_tab_text)
        self.tabWidget.addTab(self.System_tab, "")
        self.Test_tab = QtWidgets.QWidget()
        self.Test_tab.setObjectName("Test_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Test_tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Test_tab_text = QtWidgets.QPlainTextEdit(self.Test_tab)
        self.Test_tab_text.setObjectName("Test_tab_text")
        self.verticalLayout_2.addWidget(self.Test_tab_text)
        self.tabWidget.addTab(self.Test_tab, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.System_tab), _translate("DockWidget", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Test_tab), _translate("DockWidget", "Strona"))
