# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\wkspaces\EPLVTS01_PY_TOOLS\Src\GUI\resources\top_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(832, 184)
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setContentsMargins(5, 10, 5, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_trace_button = QtWidgets.QPushButton(self.tab)
        self.add_trace_button.setObjectName("add_trace_button")
        self.horizontalLayout.addWidget(self.add_trace_button)
        self.add_debug_console = QtWidgets.QPushButton(self.tab)
        self.add_debug_console.setObjectName("add_debug_console")
        self.horizontalLayout.addWidget(self.add_debug_console)
        self.add_plot_button = QtWidgets.QPushButton(self.tab)
        self.add_plot_button.setObjectName("add_plot_button")
        self.horizontalLayout.addWidget(self.add_plot_button)
        spacerItem = QtWidgets.QSpacerItem(568, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        TabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        TabWidget.addTab(self.tab_2, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget"))
        self.add_trace_button.setText(_translate("TabWidget", "Add trace"))
        self.add_debug_console.setText(_translate("TabWidget", "Add debug console"))
        self.add_plot_button.setText(_translate("TabWidget", "Add plot"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Strona"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), _translate("TabWidget", "Strona"))
